### PR TITLE
added detailed instructions for linux build

### PR DESCRIPTION
**Pull request by rashedmyt**

### CODE REVIEW

**Comment by rashedmyt** [comment]
@ZedPea added instructions for linux build as detail as possible..

**Comment by woodyjon** [comment]
Strange to me to explain in detail to users how to install golang, their website does a good job at it, and how to install qt and the go/qt bindings, it is explained in details on https://github.com/therecipe/qt/wiki/. Detailing it ourselves means that everytime something changes about those installations, we must update. And if users have problems installing them, they will ask here instead of checking the issues in those projects.

**Comment by woodyjon** [comment]
And now it looks like we need Linux to build, while before, the explanation was valid for mac and windows as well. Which is a direct consequence of my above point.

**Comment by woodyjon** [comment]
Please try to avoid regression as much as possible. A user contacted me for building on windows as the instructions for win and mac disappeared with this PR.
I added them back here: https://github.com/turtlecoin/turtle-wallet-go/commit/e804e4cf4ea2520af4070ed56d466251ddb0c709
(I left your detailed instructions for linux. I just added some spaces for consistency)

**Pull request merged**
